In [44]:
import pandas as pd

In [45]:
dataset=pd.read_csv(r"C:\Users\wwrao\OneDrive\Documents\email_spam.csv")

In [46]:
dataset=dataset.iloc[:,1:3]

In [47]:
dataset.head()

text      type
0  Hi James,\n\nHave you claim your complimentary...      spam
1  \nalt_text\nCongratulations, you just earned\n...  not spam
2  Here's your GitHub launch code, @Mortyj420!\n ...  not spam
3  Hello,\n \nThank you for contacting the Virtua...  not spam
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
c=CountVectorizer()

In [50]:
sparse_vector=c.fit_transform(dataset["text"])

In [51]:
c.vocabulary_    # vocabualry gives tell which unique_word take which index in after transforming

{'hi': 1221,
 'james': 1388,
 'have': 1196,
 'you': 2836,
 'claim': 590,
 'your': 2838,
 'complimentary': 651,
 'gift': 1126,
 'yet': 2832,
 've': 2717,
 'compiled': 647,
 'in': 1290,
 'here': 1218,
 'special': 2384,
 'astrology': 354,
 'that': 2543,
 'predicts': 1961,
 'everything': 968,
 'about': 169,
 'the': 2544,
 'future': 1103,
 'this': 2557,
 'is': 1372,
 'enabler': 918,
 'to': 2587,
 'take': 2506,
 'correct': 711,
 'actions': 198,
 'now': 1751,
 'click': 602,
 'copy': 706,
 'yours': 2840,
 'and': 285,
 'thank': 2541,
 'me': 1625,
 'later': 1471,
 'love': 1549,
 'heather': 1207,
 'alt_text': 265,
 'congratulations': 667,
 'just': 1424,
 'earned': 875,
 '500': 110,
 'completed': 649,
 'following': 1064,
 'offer': 1770,
 'view': 2734,
 'points': 1936,
 'history': 1231,
 'stop': 2437,
 'recieving': 2097,
 'notifications': 1748,
 'when': 2788,
 'earn': 874,
 'please': 1927,
 'visit': 2745,
 'profile': 1998,
 'preferences': 1963,
 'change': 565,
 'setting': 2282,
 'room': 2209,
 '120

In [52]:
numpy_array=sparse_vector.toarray()

In [53]:
numpy_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
data=pd.DataFrame({"text":["people watch youtube","youtube watch youtube","people write comment","youtube write the comment"]})

In [55]:
data

text
0       people watch youtube
1      youtube watch youtube
2       people write comment
3  youtube write the comment

In [56]:
bag_of_word=c.fit_transform(data["text"]).toarray()
bag_of_word

array([[0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 2],
       [1, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 1]], dtype=int64)

In [57]:
data["text"].unique()

array(['people watch youtube', 'youtube watch youtube',
       'people write comment', 'youtube write the comment'], dtype=object)

In [58]:
print(c.vocabulary_)  # show the index position

{'people': 1, 'watch': 3, 'youtube': 5, 'write': 4, 'comment': 0, 'the': 2}


In [59]:
bag_of_word[0] #'people watch youtube'

array([0, 1, 0, 1, 0, 1], dtype=int64)

In [60]:
bag_of_word[1] # youtube is 2 times so its number is 2

array([0, 0, 0, 1, 0, 2], dtype=int64)

In [61]:
bag_of_word[2]#people write comment

array([1, 1, 0, 0, 1, 0], dtype=int64)

In [62]:
bag_of_word[3]#youtube write the comment

array([1, 0, 1, 0, 1, 1], dtype=int64)

In [68]:
c.transform(["watch youtube write  the comment the people "]).toarray()

array([[1, 1, 2, 1, 1, 1]], dtype=int64)

In [69]:
c.transform(["watch youtube and write the comment the people "]).toarray() # remove rhe new word 

array([[1, 1, 2, 1, 1, 1]], dtype=int64)