In [1]:
import pandas as pd 


In [2]:
dataset=pd.read_csv(r"C:\Users\wwrao\OneDrive\Documents\IMDB Dataset.csv")

In [25]:
dataset=dataset.iloc[:10000,:]

## Remove html tags

In [26]:
dataset["review"] = dataset["review"].apply(lambda x: re.sub(r"<.*?>", "", x))

In [27]:
dataset["review"]

0       One of the other reviewers has mentioned that ...
1       A wonderful little production. The filming tec...
2       I thought this was a wonderful way to spend ti...
3       Basically there's a family where a little boy ...
4       Petter Mattei's "Love in the Time of Money" is...
                              ...                        
9995    Fun, entertaining movie about WWII German spy ...
9996    Give me a break. How can anyone say that this ...
9997    This movie is a bad movie. But after watching ...
9998    This is a movie that was probably made to ente...
9999    Smashing film about film-making. Shows the int...
Name: review, Length: 10000, dtype: object

## Remove url

In [28]:
def remove_url(text):
    plain_text=re.sub(r'http[s]?://\S+', '', text)
    return plain_text

In [29]:
dataset["review"]=dataset["review"].apply(remove_url)

## Remove duplicated rows

In [30]:
dataset.duplicated().sum()

17

In [32]:
dataset.drop_duplicates(inplace=True)

In [33]:
dataset.shape

(9983, 2)

##  Give the lower word

In [35]:
dataset["review"]=dataset["review"].str.lower()

In [36]:
dataset.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [37]:
import nltk
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

# Function to remove stop words
def remove_stopwords(text):
    words = text.split()
    x = [word for word in words if word.lower() not in stop_words]
    return " ".join(x)

In [40]:
dataset["review"]=dataset["review"].apply(remove_stopwords)

In [42]:
dataset.head(10)

review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. filming technique...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive
5  probably all-time favorite movie, story selfle...  positive
6  sure would like see resurrection dated seahunt...  positive
7  show amazing, fresh & innovative idea 70's fir...  negative
8  encouraged positive comments film looking forw...  negative
9  like original gut wrenching laughter like movi...  positive

In [49]:
x=dataset["review"]
x.head()

0    one reviewers mentioned watching 1 oz episode ...
1    wonderful little production. filming technique...
2    thought wonderful way spend time hot summer we...
3    basically there's family little boy (jake) thi...
4    petter mattei's "love time money" visually stu...
Name: review, dtype: object

In [51]:
y=dataset["sentiment"]
y.head()

0    positive
1    positive
2    positive
3    negative
4    positive
Name: sentiment, dtype: object

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
l=LabelEncoder()

In [56]:
y=l.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

## Vectorize using bag of word

In [59]:
from sklearn.feature_extraction.text import CountVectorizer

In [60]:
c=CountVectorizer()

In [64]:
x_train_vectorized=c.fit_transform(x_train).toarray()

In [65]:
x_test_vectorized=c.transform(x_test).toarray()

In [67]:
x_train_vectorized.shape

(7487, 46929)

## Model

In [68]:
from sklearn.naive_bayes import GaussianNB

In [69]:
g=GaussianNB()

In [71]:
g.fit(x_train_vectorized,y_train)

GaussianNB()

In [76]:
y_pred=g.predict(x_test_vectorized)

In [79]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [78]:
accuracy_score(y_test,y_pred)

0.6225961538461539

In [80]:
confusion_matrix(y_test,y_pred)

array([[900, 358],
       [584, 654]], dtype=int64)

**Using Random Forest Classifier**

In [81]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
r=RandomForestClassifier()

In [83]:
r.fit(x_train_vectorized,y_train)

RandomForestClassifier()

In [86]:
y_predict=r.predict(x_test_vectorized)
y_predict

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [87]:
accuracy_score(y_test,y_predict)

0.8493589743589743

## use frequent words in the corpus to see the accuracy score

In [88]:
c=CountVectorizer(max_features=3000)

In [112]:
x_train_max_feature=c.fit_transform(x_train).toarray()


In [113]:
x_test_max_feature=c.fit_transform(x_test).toarray()

In [114]:
x_train_max_feature.shape

(7487, 3000)

In [115]:
g=GaussianNB()

In [116]:
g.fit(x_train_max_feature,y_train)

GaussianNB()

In [117]:
y_pred=g.predict(x_test_max_feature)
y_pred

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [118]:
accuracy_score(y_test,y_pred)

0.4823717948717949

**Random forest Classifier**


In [119]:
r=RandomForestClassifier()

In [120]:
r.fit(x_train_max_feature,y_train)

RandomForestClassifier()

In [121]:
y_predict=r.predict(x_test_max_feature)

In [122]:
accuracy_score(y_test,y_predict)

0.5424679487179487

## Apply n_gram range 

In [135]:
c=CountVectorizer(ngram_range=(1,1))

In [136]:
x_train_ngram=c.fit_transform(x_train).toarray()
x_train_ngram

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [137]:
x_test_ngram=c.transform(x_test).toarray()

In [139]:
r=RandomForestClassifier()

In [140]:
r.fit(x_train_ngram,y_train)

RandomForestClassifier()

In [144]:
y_pred=r.predict(x_test_ngram)

In [145]:
accuracy_score(y_test,y_pred)

0.8525641025641025

## using tf-idf vectorizer

In [147]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [167]:
tf=TfidfVectorizer(max_features=5000)

In [168]:
x_train_tdf=tf.fit_transform(x_train).toarray()
x_train_tdf[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [169]:
x_test_tdf=tf.fit_transform(x_test).toarray()

In [170]:
r=RandomForestClassifier()

In [171]:
r.fit(x_train_tdf,y_train)

RandomForestClassifier()

In [172]:
y_pred=r.predict(x_test_tdf)
y_pred

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [173]:
accuracy_score(y_test,y_pred)

0.5272435897435898